[server]
# Sirve ./static/* en /app/static/* (avatar.glb para el componente Three.js)
enableStaticServing = true

[theme]
base = "light"
primaryColor = "#124796"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F6FA"
textColor = "#14253D"
font = "sans serif"

[client]
toolbarMode = "minimal"
